theme: jekyll-theme-hacker
title: EMPIRE BREAKOUT
description: Empire Breakout Penetration Testing Walkthrough.
show_downloads: false
baseurl: "/Empire-BreakOut"
url: ""  # Set to your GitHub Pages URL if needed

# GitHub Pages compatible plugins
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag

# Optional: custom metadata for your write-ups
author:
  name: itstallam
  url: https://github.com/itstallam

# Hacker theme extras
show_downloads: false
google_analytics:
